-- Aggregate behavior to create one row per customer

CREATE OR REPLACE TABLE CUSTOMER_SEGMENTS AS
SELECT
    CUSTOMER_ID,
    COUNT(ORDER_ID)  AS PURCHASE_COUNT,
    AVG(ORDER_VALUE) AS AVG_ORDER_VALUE
FROM CUSTOMER_ORDERS
--WHERE ORDER_DATE BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY CUSTOMER_ID;