CREATE OR REPLACE TABLE CUSTOMER_SEGMENTS_TRAIN AS
SELECT
    CUSTOMER_ID,
    PURCHASE_COUNT,
    AVG_ORDER_VALUE,
    IFF(PURCHASE_COUNT >= 3, 1, 0) AS TARGET_HIGH_VALUE
FROM CUSTOMER_SEGMENTS;